import os
import json
import asyncio
import urllib.request
from openai import AsyncOpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize async OpenAI client
client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Paths to the Remotion project
PROJECT_DIR = "c:/Users/user/OneDrive/Desktop/에이전트프로젝트/spring-greens-video"
IMG_DIR = os.path.join(PROJECT_DIR, "public", "images", "generated")
AUDIO_DIR = os.path.join(PROJECT_DIR, "public", "audio", "generated")

os.makedirs(IMG_DIR, exist_ok=True)
os.makedirs(AUDIO_DIR, exist_ok=True)

async def generate_single_image(prompt: str, index: int):
    print(f"[{index}] Generating image...")
    try:
        response = await client.images.generate(
            model="dall-e-3",
            prompt=prompt,
            size="1024x1792", # 9:16 aspect ratio roughly
            quality="standard",
            n=1,
        )
        image_url = response.data[0].url
        filepath = os.path.join(IMG_DIR, f"scene_{index:02d}.jpg")
        
        # Download image
        urllib.request.urlretrieve(image_url, filepath)
        print(f"[{index}] ✅ Saved: {filepath}")
        return filepath
    except Exception as e:
        print(f"[{index}] ❌ Failed: {e}")
        return None

async def generate_tts(text: str, index: int, voice="ko-KR-SunHiNeural"):
    filepath = os.path.join(AUDIO_DIR, f"voice_{index:02d}.mp3")
    print(f"[{index}] Generating TTS...")
    
    # Using edge-tts CLI tool
    cmd = f'edge-tts --voice "{voice}" --text "{text}" --write-media "{filepath}"'
    os.system(cmd)
    
    print(f"[{index}] ✅ Saved TTS: {filepath}")
    return filepath

async def main():
    # Example input data mapping (In production, this comes from Opal JSON Webhook + User Script)
    input_data = {
        "title": "시니어 파크골프 꿀팁",
        "scenes": [
            {
                "id": 0,
                "type": "video",
                "source": "opal_hook.mp4", # Opal generated 8s Video 1
                "script": "요즘 파크골프장 가보면, 관절이 아파서 제대로 못치시는 분들 정말 많으시죠?"
            },
            {
                "id": 1,
                "type": "image",
                "image_prompt": "A highly realistic, bright cinematic image of a smiling Korean senior woman rubbing her knees on a sunny golf course. No text.",
                "script": "병원비 걱정에, 좋아하시는 운동도 맘 편히 못하시고요."
            },
            {
                "id": 2,
                "type": "image",
                "image_prompt": "A cinematic close up of a Korean senior's hand taking some vitamins. Natural sunlight.",
                "script": "하지만 걱정 마세요. 정부에서 지원하는 맞춤형 의료비 제도가 있습니다."
            },
            {
                "id": 3,
                "type": "video",
                "source": "opal_climax.mp4", # Opal generated 8s Video 2
                "script": "신청 방법만 알면, 최대 80%까지 지원받아 시원하게 골프채 휘두르실 수 있습니다."
            }
            # ... 22 more scenes would be generated by Opal
        ]
    }

    print("🚀 Starting Hybrid Assets Generation Pipeline...")
    
    tasks = []
    # 1. Generate Images in Parallel
    for scene in input_data["scenes"]:
        if scene["type"] == "image":
            task = generate_single_image(scene["image_prompt"], scene["id"])
            tasks.append(task)
            
    # Wait for all image generation to complete
    if tasks:
        await asyncio.gather(*tasks)

    # 2. Generate TTS (Sequential to avoid rate limit or CLI collisions, though edge_tts is robust)
    for scene in input_data["scenes"]:
        await generate_tts(scene["script"], scene["id"])

    # 3. Export composition mapping for Remotion
    remotion_data_path = os.path.join(PROJECT_DIR, "src", "hybrid_script.json")
    with open(remotion_data_path, 'w', encoding='utf-8') as f:
        json.dump(input_data, f, ensure_ascii=False, indent=2)
        
    print(f"🎉 Pipeline Complete! Assets saved to {PROJECT_DIR}/public/")
    print(f"📝 Remotion mappings saved to {remotion_data_path}")

if __name__ == "__main__":
    asyncio.run(main())
